// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.13.0
// source: pdfcompose.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImagePDFService_UploadImages_FullMethodName = "/pdfcompose.ImagePDFService/UploadImages"
)

// ImagePDFServiceClient is the client API for ImagePDFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImagePDFServiceClient interface {
	UploadImages(ctx context.Context, in *ImageUploadRequest, opts ...grpc.CallOption) (*PDFResponse, error)
}

type imagePDFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImagePDFServiceClient(cc grpc.ClientConnInterface) ImagePDFServiceClient {
	return &imagePDFServiceClient{cc}
}

func (c *imagePDFServiceClient) UploadImages(ctx context.Context, in *ImageUploadRequest, opts ...grpc.CallOption) (*PDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PDFResponse)
	err := c.cc.Invoke(ctx, ImagePDFService_UploadImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImagePDFServiceServer is the server API for ImagePDFService service.
// All implementations must embed UnimplementedImagePDFServiceServer
// for forward compatibility.
type ImagePDFServiceServer interface {
	UploadImages(context.Context, *ImageUploadRequest) (*PDFResponse, error)
	mustEmbedUnimplementedImagePDFServiceServer()
}

// UnimplementedImagePDFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImagePDFServiceServer struct{}

func (UnimplementedImagePDFServiceServer) UploadImages(context.Context, *ImageUploadRequest) (*PDFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadImages not implemented")
}
func (UnimplementedImagePDFServiceServer) mustEmbedUnimplementedImagePDFServiceServer() {}
func (UnimplementedImagePDFServiceServer) testEmbeddedByValue()                         {}

// UnsafeImagePDFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagePDFServiceServer will
// result in compilation errors.
type UnsafeImagePDFServiceServer interface {
	mustEmbedUnimplementedImagePDFServiceServer()
}

func RegisterImagePDFServiceServer(s grpc.ServiceRegistrar, srv ImagePDFServiceServer) {
	// If the following call pancis, it indicates UnimplementedImagePDFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImagePDFService_ServiceDesc, srv)
}

func _ImagePDFService_UploadImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagePDFServiceServer).UploadImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImagePDFService_UploadImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagePDFServiceServer).UploadImages(ctx, req.(*ImageUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImagePDFService_ServiceDesc is the grpc.ServiceDesc for ImagePDFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImagePDFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdfcompose.ImagePDFService",
	HandlerType: (*ImagePDFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadImages",
			Handler:    _ImagePDFService_UploadImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pdfcompose.proto",
}
