// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.13.0
// source: pdfcompose.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImagePDFService_UploadImages_FullMethodName = "/pdfcompose.ImagePDFService/UploadImages"
)

// ImagePDFServiceClient is the client API for ImagePDFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImagePDFServiceClient interface {
	UploadImages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, PDFResponse], error)
}

type imagePDFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImagePDFServiceClient(cc grpc.ClientConnInterface) ImagePDFServiceClient {
	return &imagePDFServiceClient{cc}
}

func (c *imagePDFServiceClient) UploadImages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, PDFResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImagePDFService_ServiceDesc.Streams[0], ImagePDFService_UploadImages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, PDFResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImagePDFService_UploadImagesClient = grpc.ClientStreamingClient[Chunk, PDFResponse]

// ImagePDFServiceServer is the server API for ImagePDFService service.
// All implementations must embed UnimplementedImagePDFServiceServer
// for forward compatibility.
type ImagePDFServiceServer interface {
	UploadImages(grpc.ClientStreamingServer[Chunk, PDFResponse]) error
	mustEmbedUnimplementedImagePDFServiceServer()
}

// UnimplementedImagePDFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImagePDFServiceServer struct{}

func (UnimplementedImagePDFServiceServer) UploadImages(grpc.ClientStreamingServer[Chunk, PDFResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadImages not implemented")
}
func (UnimplementedImagePDFServiceServer) mustEmbedUnimplementedImagePDFServiceServer() {}
func (UnimplementedImagePDFServiceServer) testEmbeddedByValue()                         {}

// UnsafeImagePDFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagePDFServiceServer will
// result in compilation errors.
type UnsafeImagePDFServiceServer interface {
	mustEmbedUnimplementedImagePDFServiceServer()
}

func RegisterImagePDFServiceServer(s grpc.ServiceRegistrar, srv ImagePDFServiceServer) {
	// If the following call pancis, it indicates UnimplementedImagePDFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImagePDFService_ServiceDesc, srv)
}

func _ImagePDFService_UploadImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImagePDFServiceServer).UploadImages(&grpc.GenericServerStream[Chunk, PDFResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImagePDFService_UploadImagesServer = grpc.ClientStreamingServer[Chunk, PDFResponse]

// ImagePDFService_ServiceDesc is the grpc.ServiceDesc for ImagePDFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImagePDFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdfcompose.ImagePDFService",
	HandlerType: (*ImagePDFServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadImages",
			Handler:       _ImagePDFService_UploadImages_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pdfcompose.proto",
}
